// <copyright file="TransactionID.cs" company="APIMatic">
// Copyright (c) APIMatic. All rights reserved.
// </copyright>
namespace RestApiClient.Standard.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using JsonSubTypes;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using RestApiClient.Standard;
    using RestApiClient.Standard.Utilities;

    /// <summary>
    /// TransactionID.
    /// </summary>
    public class TransactionID
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionID"/> class.
        /// </summary>
        public TransactionID()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionID"/> class.
        /// </summary>
        /// <param name="epTransactionID">epTransactionID.</param>
        /// <param name="merchantTransactionID">merchantTransactionID.</param>
        public TransactionID(
            long? epTransactionID = null,
            string merchantTransactionID = null)
        {
            this.EpTransactionID = epTransactionID;
            this.MerchantTransactionID = merchantTransactionID;
        }

        /// <summary>
        /// The payment ID generated by EPS.
        /// </summary>
        [JsonProperty("epTransactionID", NullValueHandling = NullValueHandling.Ignore)]
        public long? EpTransactionID { get; set; }

        /// <summary>
        /// The unique reference of a transaction provided by the merchant. This is unique per Contracting Merchant.
        /// </summary>
        [JsonProperty("merchantTransactionID", NullValueHandling = NullValueHandling.Ignore)]
        public string MerchantTransactionID { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();

            this.ToString(toStringOutput);

            return $"TransactionID : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }

            if (obj == this)
            {
                return true;
            }

            return obj is TransactionID other &&
                ((this.EpTransactionID == null && other.EpTransactionID == null) || (this.EpTransactionID?.Equals(other.EpTransactionID) == true)) &&
                ((this.MerchantTransactionID == null && other.MerchantTransactionID == null) || (this.MerchantTransactionID?.Equals(other.MerchantTransactionID) == true));
        }
        

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"this.EpTransactionID = {(this.EpTransactionID == null ? "null" : this.EpTransactionID.ToString())}");
            toStringOutput.Add($"this.MerchantTransactionID = {(this.MerchantTransactionID == null ? "null" : this.MerchantTransactionID == string.Empty ? "" : this.MerchantTransactionID)}");
        }
    }
}